import { Case, Provider, ROLES } from "@/config/rcms";

export const mockCases: Case[] = [
  {
    id: "CASE-2024-001",
    firmId: "firm-001",
    onsetOfService: "2024-01-15",
    client: {
      rcmsId: "RC-89234",
      attyRef: "ATT-2024-045",
      dobMasked: "01/XX/1985",
      gender: "female",
      state: "CA",
      fullName: "Alice Barnes",
      displayNameMasked: "A*** B***",
    },
    intake: {
      incidentType: "MVA",
      incidentDate: "2024-01-15",
      initialTreatment: "ED",
      injuries: ["Whiplash", "Lower back pain", "Shoulder strain"],
      severitySelfScore: 7,
    },
    fourPs: {
      physical: 7,
      psychological: 5,
      psychosocial: 4,
      professional: 6,
    },
    sdoh: {
      housing: false,
      food: false,
      transport: true,
      insuranceGap: true,
    },
    demographics: {
      zip3: "900",
      ageBand: "35-44",
      gender: "female",
      raceEthnicity: ["White"],
      education: "bachelor",
      incomeBand: "75-99k",
      consentForDeidentifiedUse: true,
    },
    consent: {
      signed: true,
      signedAt: "2024-01-20T10:30:00Z",
      scope: {
        shareWithAttorney: true,
        shareWithProviders: true,
      },
    },
    flags: ["High Pain", "Transportation Need"],
    sdohFlags: ["Transportation", "Money/Cost"],
    riskLevel: "at_risk",
    assignedProviderId: "PROV-001",
    status: "IN_PROGRESS",
    designatedAttorneyId: "ATT-001",
    checkins: [
      {
        ts: "2024-02-01T09:00:00Z",
        pain: 7,
        note: "Still experiencing significant pain, attending PT twice weekly",
      },
      {
        ts: "2024-02-15T14:30:00Z",
        pain: 6,
        note: "Some improvement, but still struggling with daily activities",
        fourPs: { physical: 6, psychological: 5 },
      },
    ],
    createdAt: "2024-01-15T08:00:00Z",
    updatedAt: "2024-02-15T14:30:00Z",
  },
  {
    id: "CASE-2024-002",
    firmId: "firm-001",
    onsetOfService: "2024-02-01",
    client: {
      rcmsId: "RC-89235",
      attyRef: "ATT-2024-046",
      dobMasked: "05/XX/1992",
      gender: "male",
      state: "TX",
      fullName: "Sam Rivera",
      displayNameMasked: "S*** R***",
    },
    intake: {
      incidentType: "WorkComp",
      incidentDate: "2024-02-01",
      initialTreatment: "UrgentCare",
      injuries: ["Rotator cuff tear", "Elbow tendonitis"],
      severitySelfScore: 8,
    },
    demographics: {
      zip3: "770",
      ageBand: "25-34",
      gender: "male",
      raceEthnicity: ["Hispanic or Latino"],
      education: "some_college",
      incomeBand: "50-74k",
      consentForDeidentifiedUse: true,
    },
    consent: {
      signed: false, // NOT SIGNED - hard block for attorneys
      scope: {
        shareWithAttorney: false,
        shareWithProviders: false,
      },
    },
    flags: ["Awaiting Consent"],
    sdohFlags: [],
    riskLevel: "stable",
    status: "AWAITING_CONSENT",
    createdAt: "2024-02-01T10:15:00Z",
    updatedAt: "2024-02-01T10:15:00Z",
  },
  {
    id: "CASE-2024-003",
    firmId: "firm-001",
    onsetOfService: "2024-01-10",
    client: {
      rcmsId: "RC-89236",
      attyRef: "ATT-2024-047",
      dobMasked: "11/XX/1978",
      gender: "nonbinary",
      state: "NY",
      fullName: "Jordan Lee",
      displayNameMasked: "J*** L***",
    },
    intake: {
      incidentType: "Other",
      incidentDate: "2024-01-10",
      initialTreatment: "PCP",
      injuries: ["PTSD", "Chronic pain", "Anxiety"],
      severitySelfScore: 9,
    },
    fourPs: {
      physical: 6,
      psychological: 9,
      psychosocial: 8,
      professional: 7,
    },
    sdoh: {
      housing: true,
      food: true,
      transport: false,
      insuranceGap: false,
    },
    demographics: {
      zip3: "100",
      ageBand: "45-54",
      gender: "prefer_not_to_say",
      raceEthnicity: ["Prefer not to say"],
      education: "prefer_not_to_say",
      incomeBand: "prefer_not_to_say",
      consentForDeidentifiedUse: false,
    },
    consent: {
      signed: true,
      signedAt: "2024-01-12T11:00:00Z",
      scope: {
        shareWithAttorney: false, // Signed but attorney sharing disabled
        shareWithProviders: true,
      },
      restrictedAccess: true,
    },
    flags: ["Sensitive Case", "Mental Health", "Housing Insecure"],
    sdohFlags: ["Housing Instability", "Child/Elder Care"],
    riskLevel: "critical",
    status: "HOLD_SENSITIVE",
    designatedAttorneyId: "ATT-002",
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-12T11:00:00Z",
  },
];

export const mockProviders: Provider[] = [
  {
    id: "PROV-001",
    name: "Dr. Sarah Chen",
    specialty: "Physical Therapy",
    city: "Los Angeles",
    state: "CA",
    distanceMiles: 5.2,
    schedulingUrl: "https://schedule.example.com/dr-chen",
    active: true,
  },
  {
    id: "PROV-002",
    name: "Dr. Michael Rodriguez",
    specialty: "Orthopedic Surgery",
    city: "San Diego",
    state: "CA",
    distanceMiles: 8.7,
    schedulingUrl: "https://schedule.example.com/dr-rodriguez",
    active: true,
  },
  {
    id: "PROV-003",
    name: "Dr. Jennifer Park",
    specialty: "Pain Management",
    city: "San Francisco",
    state: "CA",
    distanceMiles: 12.3,
    active: true,
  },
  {
    id: "PROV-004",
    name: "Dr. David Thompson",
    specialty: "Chiropractic",
    city: "Houston",
    state: "TX",
    distanceMiles: 3.4,
    schedulingUrl: "https://schedule.example.com/dr-thompson",
    active: true,
  },
  {
    id: "PROV-005",
    name: "Dr. Emily Watson",
    specialty: "Psychology",
    city: "New York",
    state: "NY",
    distanceMiles: 6.1,
    schedulingUrl: "https://schedule.example.com/dr-watson",
    active: true,
  },
];

export const mockUsers = [
  { id: "ATT-001", name: "James Morrison", role: ROLES.ATTORNEY, email: "j.morrison@firm.com" },
  { id: "ATT-002", name: "Lisa Chen", role: ROLES.ATTORNEY, email: "l.chen@firm.com" },
  { id: "RN-001", name: "Maria Garcia", role: ROLES.RN_CM, email: "m.garcia@rcms.com" },
  { id: "STAFF-001", name: "Robert Johnson", role: ROLES.STAFF, email: "r.johnson@rcms.com" },
  { id: "ADMIN-001", name: "Admin User", role: ROLES.SUPER_ADMIN, email: "admin@rcms.com" },
];
